#include "GameplayTagTSGenSubsystem.h"
#include "GameplayTagGenSettings.h"
#include "GameplayTagsManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

namespace
{
	// 将 GameplayTag 名转换为合法的 TS 标识符：
	// 仅保留字母/数字/下划线，其余字符（'.'、'-' 等）替换为 '_'；首字符为数字时加 '_' 前缀
	FString MakeTSIdentifier(const FString& TagName)
	{
		FString Result;
		Result.Reserve(TagName.Len());
		for (const TCHAR Char : TagName)
		{
			Result.AppendChar((FChar::IsAlnum(Char) || Char == TEXT('_')) ? Char : TEXT('_'));
		}
		if (!Result.IsEmpty() && FChar::IsDigit(Result[0]))
		{
			Result = FString(TEXT("_")) + Result;
		}
		return Result;
	}
}

void UGameplayTagTSGenSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{
	Super::Initialize(Collection);

	// 监听 Tag 树刷新
	UGameplayTagsManager::OnEditorRefreshGameplayTagTree.AddUObject(
		this, &UGameplayTagTSGenSubsystem::TriggerGenerateWithDebounce);

	// 触发初始生成
	TriggerGenerateWithDebounce();
}

void UGameplayTagTSGenSubsystem::Deinitialize()
{
	UGameplayTagsManager::OnEditorRefreshGameplayTagTree.RemoveAll(this);

	// 清理注册的 Ticker
	if (DebounceTickerHandle.IsValid())
	{
		FTSTicker::GetCoreTicker().RemoveTicker(DebounceTickerHandle);
		DebounceTickerHandle.Reset();
	}

	Super::Deinitialize();
}

void UGameplayTagTSGenSubsystem::TriggerGenerateWithDebounce()
{
	// 如果之前已有排队的延迟任务，先移除（防抖）
	if (DebounceTickerHandle.IsValid())
	{
		FTSTicker::GetCoreTicker().RemoveTicker(DebounceTickerHandle);
		DebounceTickerHandle.Reset();
	}

	// 延迟 0.5 秒后在主线程安全执行生成
	// FTSTicker 属于 Core 模块，引擎启动的任何阶段都可以安全调用，绝不会报空指针崩溃
	DebounceTickerHandle = FTSTicker::GetCoreTicker().AddTicker(
		FTickerDelegate::CreateWeakLambda(this, [this](float DeltaTime) -> bool
			{
				GenerateGameplayTagTS();
				DebounceTickerHandle.Reset();
				return false; // 返回 false 表示只执行一次（不循环）
			}),
		0.5f // 延迟 0.5 秒防抖
	);
}

void UGameplayTagTSGenSubsystem::GenerateGameplayTagTS()
{
	FGameplayTagContainer TagContainer;
	UGameplayTagsManager::Get().RequestAllGameplayTags(TagContainer, true);

	FString TSContent;
	TSContent += TEXT("// [Auto-Generated by PuertsTagGenerator Plugin] DO NOT MODIFY MANUALLY!\n");
	TSContent += TEXT("import * as UE from 'ue';\n\n");

	// 辅助构造函数：必须用 new UE.GameplayTag() 创建真实结构体实例。
	// 直接写 { TagName: "..." } as any as UE.GameplayTag 虽能骗过 tsc，
	// 但运行时是普通 JS 对象，传给 GAS 的 C++ API 会类型不匹配甚至崩溃。
	TSContent += TEXT("function _createTag(name: string): UE.GameplayTag {\n");
	TSContent += TEXT("    const tag = new UE.GameplayTag();\n");
	TSContent += TEXT("    tag.TagName = name;\n");
	TSContent += TEXT("    return tag;\n");
	TSContent += TEXT("}\n\n");

	// 换成专属命名：TagsfromPlugin
	TSContent += TEXT("export const TagsfromPlugin = {\n");

	// 按名称排序，保证多次生成结果稳定（避免无意义的文件 diff）
	TArray<FGameplayTag> SortedTags;
	TagContainer.GetGameplayTagArray(SortedTags);
	SortedTags.Sort([](const FGameplayTag& A, const FGameplayTag& B)
	{
		return A.ToString() < B.ToString();
	});

	TSet<FString> UsedIdentifiers;
	for (const FGameplayTag& Tag : SortedTags)
	{
		FString TagStr = Tag.ToString();
		FString Identifier = MakeTSIdentifier(TagStr);

		// 极少数情况下不同 Tag 会映射出同一标识符（如 A.B 与 A_B），追加数字后缀避免重复键
		const FString BaseIdentifier = Identifier;
		int32 Suffix = 2;
		while (UsedIdentifiers.Contains(Identifier))
		{
			Identifier = FString::Printf(TEXT("%s_%d"), *BaseIdentifier, Suffix++);
		}
		UsedIdentifiers.Add(Identifier);

		TSContent += FString::Printf(
			TEXT("    /** Tag: %s */\n    %s: _createTag(\"%s\"),\n"),
			*TagStr,
			*Identifier,
			*TagStr
		);
	}

	TSContent += TEXT("} as const;\n\n");

	// 先导出类型别名，再在 declare global 中引用它。
	// 不能写 typeof TagsfromPlugin —— 那样会引用到全局常量自身，构成循环类型引用（TS2502）
	TSContent += TEXT("export type TTagsfromPlugin = typeof TagsfromPlugin;\n\n");

	// 全局挂载与声明
	TSContent += TEXT("(globalThis as any).TagsfromPlugin = TagsfromPlugin;\n\n");
	TSContent += TEXT("declare global {\n");
	TSContent += TEXT("    const TagsfromPlugin: TTagsfromPlugin;\n");
	TSContent += TEXT("}\n");

	const UGameplayTagGenSettings* Settings = GetDefault<UGameplayTagGenSettings>();
	FString RelativePath = Settings->OutputFilePath.FilePath;
	if (RelativePath.IsEmpty())
	{
		RelativePath = TEXT("TypeScript/Gen/GameplayTags.gen.ts");
	}

	FString FinalOutputPath = FPaths::Combine(FPaths::ProjectDir(), RelativePath);

	// 内容未变化时跳过写盘，避免每次刷新 Tag 树都重写文件
	FString OldContent;
	if (FFileHelper::LoadFileToString(OldContent, *FinalOutputPath) && OldContent == TSContent)
	{
		return;
	}

	if (FFileHelper::SaveStringToFile(TSContent, *FinalOutputPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
	{
		UE_LOG(LogTemp, Display, TEXT("[PuertsTagGenerator] Successfully generated GameplayTags at: %s"), *FinalOutputPath);
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("[PuertsTagGenerator] Failed to write file at: %s"), *FinalOutputPath);
	}
}